-- ================================================================
-- PROJECT: Live Broadcaster Engagement & Monetization Pipeline
-- TOURNAMENT: 2026 FIFA World Cup
-- AUTHOR: Vishnu Gautam
-- DATABASE: MySQL 8.0
-- CREATED: June 2026
--
-- BUSINESS QUESTION:
-- Which World Cup matches represent the highest-value advertising
-- inventory for broadcasters, and how do we quantify that in real time?
--
-- DATA SOURCES:
-- 1. openfootball/worldcup.json (GitHub) - live match fixtures & scores
-- 2. Manual Elo ratings table - pre-tournament team strength ratings
-- 3. Manual team_groups table - official FIFA group draw (Dec 5, 2025)
--
-- PIPELINE OVERVIEW:
-- extract_matches.py → matches.csv → MySQL → final_standings.csv
--                                          → high_engagement_matches.csv
-- ================================================================


-- ================================================================
-- PHASE 0: DATABASE SETUP
-- ================================================================

-- Create the project database.
-- utf8mb4 character set is used instead of plain utf8 because it
-- supports the full Unicode range including special characters in
-- team names like Curaçao, Côte d'Ivoire, Türkiye.
-- Without this, MySQL silently truncates or errors on these characters.

CREATE DATABASE worldcup
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE worldcup;


-- ================================================================
-- PHASE 1: DIMENSION TABLE — team_groups
--
-- PURPOSE:
-- Maps all 48 World Cup teams to their group (A–L).
-- Source: Official FIFA draw, December 5, 2025. Groups are fixed
-- and do not change during the tournament.
--
-- WHY A SEPARATE TABLE?
-- The match fixture data (from openfootball) does not include a
-- reliable group field — it uses "Matchday 1", "Matchday 2" etc.
-- to describe rounds, not "Group A", "Group B". Rather than
-- hard-coding group names into every query, we create a single
-- reference (dimension) table and JOIN to it. This is the standard
-- data warehousing pattern: one source of truth for reference data.
--
-- WHY VARCHAR(100) NOT TEXT?
-- VARCHAR is more efficient for short, fixed-length strings and
-- allows use as a PRIMARY KEY. TEXT columns cannot be primary keys
-- in MySQL without a prefix length.
-- ================================================================

CREATE TABLE IF NOT EXISTS team_groups (
    team_name  VARCHAR(100) PRIMARY KEY,
    group_name CHAR(1) NOT NULL
);

INSERT INTO team_groups (team_name, group_name) VALUES
-- Group A
('Mexico','A'), ('South Africa','A'), ('South Korea','A'), ('Czechia','A'),
-- Group B
('Canada','B'), ('Bosnia and Herzegovina','B'), ('Qatar','B'), ('Switzerland','B'),
-- Group C
('Brazil','C'), ('Morocco','C'), ('Haiti','C'), ('Scotland','C'),
-- Group D
('USA','D'), ('Paraguay','D'), ('Australia','D'), ('Turkey','D'),
-- Group E
('Germany','E'), ('Curacao','E'), ('Ivory Coast','E'), ('Ecuador','E'),
-- Group F
('Netherlands','F'), ('Japan','F'), ('Sweden','F'), ('Tunisia','F'),
-- Group G
('Belgium','G'), ('Egypt','G'), ('Iran','G'), ('New Zealand','G'),
-- Group H
('Spain','H'), ('Cape Verde','H'), ('Saudi Arabia','H'), ('Uruguay','H'),
-- Group I
('France','I'), ('Senegal','I'), ('Iraq','I'), ('Norway','I'),
-- Group J
('Argentina','J'), ('Algeria','J'), ('Austria','J'), ('Jordan','J'),
-- Group K
('Portugal','K'), ('DR Congo','K'), ('Uzbekistan','K'), ('Colombia','K'),
-- Group L
('England','L'), ('Croatia','L'), ('Ghana','L'), ('Panama','L');

-- VERIFY: Should return 48
SELECT COUNT(*) AS total_teams FROM team_groups;


-- ================================================================
-- PHASE 2: IMPORT raw_matches
--
-- matches.csv was generated by extract_matches.py (see project root).
-- It was imported manually using:
-- MySQL Workbench → Right-click Tables → Table Data Import Wizard
-- → Select matches.csv → New table: raw_matches
--
-- IMPORTANT SETTING DURING IMPORT:
-- home_goals and away_goals must be set to TEXT type in the
-- Column Mappings screen of the import wizard — NOT integer.
-- Reason: upcoming matches have blank/empty values in these columns.
-- If MySQL tries to import blank as INTEGER, it either errors or
-- silently inserts 0, which would make unplayed matches appear to
-- have ended 0-0. We handle type conversion properly in SQL (below).
--
-- ERROR ENCOUNTERED #1: Encoding error during first import attempt
-- Error: "Unhandled exception: 'ascii' codec can't decode byte 0xc3
--         in position 1610: ordinal not in range(128)"
-- Cause: The CSV contained special characters (ç in Curaçao) that
--        MySQL Workbench's import wizard could not read as ASCII.
-- Fix: Regenerated matches.csv from Python with special characters
--      replaced (ç→c, ô→o etc.) and saved with utf-8 encoding.
--      Team name became "Curacao" instead of "Curaçao" — acceptable
--      since our reference tables also use the ASCII version.
--
-- ERROR ENCOUNTERED #2: First export had only 73 rows instead of 104
-- Cause: The Python script was filtering out upcoming matches that
--        had empty goal fields when saving with ASCII encoding.
-- Fix: Explicitly wrote empty string '' for NULL goals instead of
--      skipping the field, ensuring all 104 rows were preserved.
-- ================================================================

-- VERIFY after import:
SELECT COUNT(*) AS total_rows FROM raw_matches;
SELECT DISTINCT status_short FROM raw_matches;
-- Expected: COUNT = 104, status_short values = 'FT' and 'NS' only


-- ================================================================
-- PHASE 3: FACT TABLE — matches_clean
--
-- PURPOSE:
-- Create a cleaned, type-enforced version of raw_matches that all
-- downstream queries use. Never query raw_matches directly after
-- this step — always use matches_clean.
--
-- KEY DECISIONS:
--
-- 1. CAST(x AS SIGNED) not CAST(x AS INTEGER)
--    MySQL's CAST() uses SIGNED/UNSIGNED for integers, not INTEGER.
--    INTEGER is SQLite syntax and does not work in MySQL.
--
-- 2. NULLIF(home_goals, '') before CAST
--    NULLIF(x, '') returns NULL if x is an empty string, otherwise
--    returns x unchanged. This is critical: CAST('' AS SIGNED) in
--    MySQL returns 0, not NULL. Without NULLIF, every upcoming match
--    would appear to have ended 0-0, corrupting all standings
--    calculations that filter on is_completed = 1.
--
-- 3. LEFT(match_date, 10) not DATE(match_date)
--    The raw match_date from openfootball is a plain YYYY-MM-DD
--    string, so LEFT(match_date, 10) safely extracts the date.
--    If using API-Football, dates come as full ISO 8601 strings
--    like "2026-06-14T19:00:00+00:00" — MySQL's DATE() function
--    can fail on the T separator and timezone offset, making LEFT()
--    the safer choice regardless of source format.
--
-- 4. group_name LIKE 'Group%' for stage_category
--    openfootball stores group names as "Group A", "Group B" etc.
--    directly in the group_name field (unlike round which says
--    "Matchday 1"). LIKE 'Group%' cleanly separates group stage
--    from knockout stage matches for the ad-slot tier logic.
-- ================================================================

CREATE TABLE matches_clean AS
SELECT
    CAST(fixture_id AS SIGNED)                    AS fixture_id,
    LEFT(match_date, 10)                          AS match_date,
    TRIM(round)                                   AS round,
    TRIM(group_name)                              AS group_name,
    TRIM(status_short)                            AS status_short,
    TRIM(home_team)                               AS home_team,
    TRIM(away_team)                               AS away_team,
    CAST(NULLIF(home_goals, '') AS SIGNED)        AS home_goals,
    CAST(NULLIF(away_goals, '') AS SIGNED)        AS away_goals,

    -- is_completed: 1 for finished matches, 0 for upcoming.
    -- Used as a filter in every downstream aggregation query to
    -- ensure we only calculate stats from played matches.
    CASE WHEN status_short = 'FT' THEN 1 ELSE 0 END AS is_completed,

    -- stage_category: classifies each match as Group Stage or
    -- Knockout Stage. Knockout matches get a higher ad-slot tier
    -- in the engagement analysis because elimination stakes drive
    -- significantly higher viewership than group stage matches.
    CASE
        WHEN group_name LIKE 'Group%' THEN 'Group Stage'
        ELSE 'Knockout Stage'
    END AS stage_category

FROM raw_matches;

-- VERIFY: null_goals_rows should equal upcoming count exactly.
-- If null_goals_rows < upcoming, NULLIF did not work correctly
-- and some unplayed matches are showing as 0-0.
SELECT
    COUNT(*)                                            AS total_fixtures,
    SUM(is_completed)                                   AS completed,
    COUNT(*) - SUM(is_completed)                        AS upcoming,
    SUM(CASE WHEN home_goals IS NULL THEN 1 ELSE 0 END) AS null_goals_rows
FROM matches_clean;
-- Expected: total=104, completed=73, upcoming=31, null_goals_rows=31


-- ================================================================
-- PHASE 4: INTERMEDIATE TABLE — team_match_stats
--
-- PURPOSE:
-- Transform match-level data (one row per match) into team-level
-- data (one row per team per match). This is the critical step
-- that makes standings aggregation possible.
--
-- WHY UNION ALL?
-- Each match involves two teams. To calculate a team's total points,
-- wins, goals etc., we need each team's result from their own
-- perspective. A single match row has home_team and away_team —
-- we need to "unfold" this into two rows, one for each team.
-- UNION ALL creates the home team's row in the first SELECT and
-- the away team's mirror-image row in the second SELECT, then
-- stacks them. Result: 73 completed matches × 2 = 146 rows.
--
-- WHY UNION ALL NOT UNION?
-- UNION removes duplicate rows. UNION ALL keeps all rows including
-- duplicates. We want ALL rows here — we are not looking for
-- unique values, we are creating two intentionally different
-- perspectives of the same match. UNION would potentially drop
-- rows where both teams had identical stats (e.g. two 0-0 draws
-- in the same group), corrupting the standings.
--
-- WHY CASE WHEN INSIDE SUM()?
-- This is the standard SQL pattern for conditional counting.
-- Instead of using COUNT() with a WHERE clause (which would
-- require a separate query per metric), CASE WHEN returns 1 or 0
-- for each row, and SUM() adds them up. One pass through the data
-- gives us wins, draws, and losses simultaneously.
-- ================================================================

CREATE TABLE team_match_stats AS

-- HOME TEAM PERSPECTIVE
-- For the home team: goals_for = home_goals, goals_against = away_goals
SELECT
    fixture_id,
    match_date,
    stage_category,
    home_team    AS team,
    away_team    AS opponent,
    home_goals   AS goals_for,
    away_goals   AS goals_against,
    CASE
        WHEN home_goals > away_goals THEN 3  -- win = 3 points
        WHEN home_goals = away_goals THEN 1  -- draw = 1 point
        ELSE 0                               -- loss = 0 points
    END AS points,
    CASE WHEN home_goals > away_goals THEN 1 ELSE 0 END AS win,
    CASE WHEN home_goals = away_goals THEN 1 ELSE 0 END AS draw,
    CASE WHEN home_goals < away_goals THEN 1 ELSE 0 END AS loss
FROM matches_clean
WHERE is_completed = 1

UNION ALL

-- AWAY TEAM PERSPECTIVE (mirror image)
-- For the away team: goals_for = away_goals, goals_against = home_goals
-- Everything is flipped — what was "home" is now "opponent"
SELECT
    fixture_id,
    match_date,
    stage_category,
    away_team    AS team,
    home_team    AS opponent,
    away_goals   AS goals_for,
    home_goals   AS goals_against,
    CASE
        WHEN away_goals > home_goals THEN 3
        WHEN away_goals = home_goals THEN 1
        ELSE 0
    END AS points,
    CASE WHEN away_goals > home_goals THEN 1 ELSE 0 END AS win,
    CASE WHEN away_goals = home_goals THEN 1 ELSE 0 END AS draw,
    CASE WHEN away_goals < home_goals THEN 1 ELSE 0 END AS loss
FROM matches_clean
WHERE is_completed = 1;

-- VERIFY: Should be 73 × 2 = 146 rows
SELECT COUNT(*) AS total_rows FROM team_match_stats;


-- ================================================================
-- PHASE 5: GROUP STANDINGS — group_standings
--
-- PURPOSE:
-- Aggregate team_match_stats into a standard football points table
-- showing each team's record across all completed group stage matches.
--
-- WHY JOIN TO team_groups HERE?
-- team_match_stats has team names but no group letters (A–L).
-- Joining to team_groups adds the group_name column so we can
-- GROUP BY group and team together. This is the dimension table
-- pattern paying off — we only need group assignments in one place.
--
-- ERROR ENCOUNTERED #3: Missing teams in group standings
-- After running this query, Group A showed only 3 teams instead of 4.
-- Czechia was missing.
-- Cause: openfootball uses "Czech Republic" but team_groups had
--        "Czechia". The JOIN failed silently — no error, just no
--        matching row, so the team was excluded from results.
--        Bosnia had the same issue: "Bosnia & Herzegovina" vs
--        "Bosnia and Herzegovina".
-- Diagnosis query used:
--   SELECT DISTINCT tms.team
--   FROM team_match_stats tms
--   LEFT JOIN team_groups tg ON tms.team = tg.team_name
--   WHERE tg.team_name IS NULL;
-- Fix: Updated team_groups to match the names used in the data.
--
-- ERROR ENCOUNTERED #4: Safe update mode blocking UPDATE statements
-- Error: "Error Code: 1175. You are using safe update mode and you
--         tried to update a table without a WHERE that uses a KEY column"
-- Cause: MySQL Workbench runs in safe update mode by default, which
--        blocks UPDATE/DELETE statements that don't use a primary key
--        in the WHERE clause. This is a safety feature to prevent
--        accidental mass updates.
-- Fix: SET SQL_SAFE_UPDATES = 0; before running UPDATE statements.
--      This disables safe mode for the current session only.
-- ================================================================

-- Fix name mismatches discovered during diagnosis (Error #3 and #4)
SET SQL_SAFE_UPDATES = 0;
UPDATE team_groups SET team_name = 'Czech Republic'      WHERE team_name = 'Czechia';
UPDATE team_groups SET team_name = 'Bosnia & Herzegovina' WHERE team_name = 'Bosnia and Herzegovina';

-- Verify no more mismatches remain
SELECT DISTINCT tms.team
FROM team_match_stats tms
LEFT JOIN team_groups tg ON tms.team = tg.team_name
WHERE tg.team_name IS NULL;
-- Expected: empty result set (no rows)

-- Create group standings
CREATE TABLE group_standings AS
SELECT
    tg.group_name,
    tms.team,
    COUNT(*)                                      AS played,
    SUM(tms.win)                                  AS wins,
    SUM(tms.draw)                                 AS draws,
    SUM(tms.loss)                                 AS losses,
    SUM(tms.goals_for)                            AS goals_for,
    SUM(tms.goals_against)                        AS goals_against,
    SUM(tms.goals_for) - SUM(tms.goals_against)   AS goal_difference,
    SUM(tms.points)                               AS points
FROM team_match_stats tms
JOIN team_groups tg ON tms.team = tg.team_name
GROUP BY tg.group_name, tms.team
ORDER BY tg.group_name,
         SUM(tms.points) DESC,
         (SUM(tms.goals_for) - SUM(tms.goals_against)) DESC;

-- VERIFY: All 12 groups should have exactly 4 teams
SELECT group_name, COUNT(*) AS team_count
FROM group_standings
GROUP BY group_name
ORDER BY group_name;

-- Spot check Group A
SELECT * FROM group_standings WHERE group_name = 'A';


-- ================================================================
-- PHASE 6: RANKED STANDINGS — final_standings
--
-- PURPOSE:
-- Add a dynamic group_rank column to group_standings using a
-- window function. Each team gets a rank (1–4) within their group
-- based on FIFA tiebreaker rules: points first, then goal
-- difference, then goals scored.
--
-- WHY A WINDOW FUNCTION INSTEAD OF A SUBQUERY?
-- A correlated subquery approach would require a separate COUNT
-- query for every single row — highly inefficient. A window function
-- processes all rows in one pass and is the standard modern SQL
-- approach for this type of ranking problem.
--
-- WHY PARTITION BY group_name?
-- Without PARTITION BY, RANK() would rank all 48 teams globally
-- (1 to 48). PARTITION BY group_name resets the ranking for each
-- group independently, giving us ranks 1–4 within each group.
-- Think of it as "GROUP BY for window functions" — it defines the
-- window (subset of rows) that each rank is calculated within.
--
-- WHY RANK() NOT ROW_NUMBER()?
-- ROW_NUMBER() always gives unique sequential numbers (1,2,3,4).
-- RANK() gives tied teams the same rank and skips the next number
-- (e.g. two teams tied for 2nd both get rank 2, next team gets 4).
-- FIFA rules can result in ties, so RANK() is more accurate here.
--
-- NOTE ON MYSQL COMPATIBILITY:
-- Window functions require MySQL 8.0+. If you see the error
-- "FUNCTION worldcup.RANK does not exist", your MySQL version
-- is below 8.0. Run SELECT VERSION(); to check.
-- ================================================================

CREATE TABLE final_standings AS
SELECT
    group_name,
    team,
    played,
    wins,
    draws,
    losses,
    goals_for,
    goals_against,
    goal_difference,
    points,

    -- THE WINDOW FUNCTION
    -- PARTITION BY: calculate rank separately for each group
    -- ORDER BY: FIFA official tiebreaker sequence
    RANK() OVER (
        PARTITION BY group_name
        ORDER BY points DESC, goal_difference DESC, goals_for DESC
    ) AS group_rank,

    -- Business interpretation for dashboard display
    CASE
        WHEN RANK() OVER (PARTITION BY group_name ORDER BY points DESC, goal_difference DESC, goals_for DESC) = 1
        THEN 'Group Leader'
        WHEN RANK() OVER (PARTITION BY group_name ORDER BY points DESC, goal_difference DESC, goals_for DESC) = 2
        THEN 'Qualification Zone'
        WHEN RANK() OVER (PARTITION BY group_name ORDER BY points DESC, goal_difference DESC, goals_for DESC) = 3
        THEN 'Best-Third Contender'
        ELSE 'Eliminated'
    END AS qualification_status

FROM group_standings;

-- VERIFY: 12 group leaders, one per group
SELECT group_name, team, points, group_rank, qualification_status
FROM final_standings
WHERE group_rank = 1
ORDER BY group_name;


-- ================================================================
-- PHASE 7: ELO RATINGS TABLE — elo_ratings
--
-- PURPOSE:
-- Store pre-tournament Elo ratings for all 48 teams. Elo ratings
-- quantify team strength on a single numerical scale. The difference
-- between two teams' ratings (the "Elo gap") measures how surprising
-- a result was — the larger the gap with the underdog winning,
-- the bigger the upset.
--
-- DATA SOURCE DECISION:
-- Original plan was to use a Kaggle dataset
-- (elo_ratings_wc2026.csv by afonsofernandescruz). After importing,
-- the dataset only contained 10 European/South American teams —
-- not all 48 World Cup participants. With only 3 of 73 completed
-- matches coverable, the dataset was unusable for full tournament
-- analysis.
-- Solution: Built a complete 48-team Elo table manually using
-- publicly available pre-tournament FIFA/Elo ranking data.
-- Ratings are approximate but consistent — sufficient for relative
-- strength comparisons which is all the upset model requires.
--
-- ERROR ENCOUNTERED #5: Name mismatches between elo_ratings and matches_clean
-- After creating the table, the join diagnostic showed almost all
-- 48 teams were unmatched. The Elo table used different naming
-- conventions (e.g. "Korea Republic" vs "South Korea", "United States"
-- vs "USA", "IR Iran" vs "Iran").
-- Fix: UPDATE statements to align elo_ratings names with the
-- names used in matches_clean (sourced from openfootball).
--
-- ERROR ENCOUNTERED #6: Duplicate entry error
-- Error: "Error Code: 1062. Duplicate entry 'Tunisia' for key
--         'elo_ratings.PRIMARY'"
-- Cause: Tunisia appeared twice in the INSERT statement by mistake.
-- Fix: Removed the duplicate INSERT row for Tunisia.
-- ================================================================

DROP TABLE IF EXISTS elo_ratings;

CREATE TABLE elo_ratings (
    team_name  VARCHAR(100) PRIMARY KEY,
    elo_rating INT
);

INSERT INTO elo_ratings (team_name, elo_rating) VALUES
('Argentina', 1891),
('France', 1860),
('Brazil', 1899),
('England', 1912),
('Belgium', 1882),
('Portugal', 1810),
('Netherlands', 1812),
('Spain', 2034),
('Uruguay', 1996),
('USA', 1650),
('Mexico', 1720),
('Germany', 1780),
('Croatia', 1780),
('Morocco', 1750),
('Switzerland', 1700),
('Japan', 1730),
('South Korea', 1650),
('Senegal', 1680),
('Colombia', 1740),
('Ecuador', 1660),
('Canada', 1640),
('Australia', 1620),
('Iran', 1640),
('Egypt', 1620),
('Turkey', 1660),
('Norway', 1700),
('Sweden', 1690),
('Austria', 1845),
('Czech Republic', 1897),
('Scotland', 1930),
('Algeria', 1630),
('Tunisia', 1600),
('Ghana', 1580),
('Ivory Coast', 1650),
('South Africa', 1550),
('DR Congo', 1540),
('Cape Verde', 1520),
('Qatar', 1480),
('Saudi Arabia', 1580),
('Iraq', 1530),
('Uzbekistan', 1510),
('Jordan', 1490),
('Panama', 1530),
('Haiti', 1470),
('Paraguay', 1620),
('Bosnia & Herzegovina', 1640),
('New Zealand', 1480),
('Curacao', 1450);

-- VERIFY: Should return 48
SELECT COUNT(*) FROM elo_ratings;

-- VERIFY: Check no mismatches with matches_clean
SELECT DISTINCT home_team
FROM matches_clean
WHERE is_completed = 1
AND home_team NOT IN (SELECT team_name FROM elo_ratings)
UNION
SELECT DISTINCT away_team
FROM matches_clean
WHERE is_completed = 1
AND away_team NOT IN (SELECT team_name FROM elo_ratings);
-- Expected: empty result set


-- ================================================================
-- PHASE 8: UPSET ANALYSIS — high_engagement_matches
--
-- PURPOSE:
-- Join completed match results with pre-tournament Elo ratings to
-- identify upset matches and assign ad-slot tiers. This table
-- directly answers the core business question: which matches are
-- the highest-value advertising inventory?
--
-- BUSINESS LOGIC:
-- Upsets generate the highest social media engagement, replay
-- demand, and viewership spikes of any match type. A broadcaster
-- that can identify high-upset-probability matches in advance can
-- charge premium CPM rates for those ad slots. This table
-- quantifies "upset magnitude" using Elo gap as the measure.
--
-- KEY CALCULATIONS:
-- elo_gap = ABS(home_elo - away_elo)
--   Measures how mismatched the two teams were on paper.
--   A gap of 100+ points means one team was a clear favourite.
--   The larger the gap with the underdog winning, the bigger
--   the upset and the higher the expected viewership spike.
--
-- upset threshold = 100 Elo points
--   Standard threshold in football analytics for "clear favourite".
--   Below 100 points difference = competitive match, result not
--   surprising regardless of who wins.
--
-- AD SLOT TIER LOGIC:
--   TIER 1 - Premium: Upset in a knockout stage match
--            (highest stakes + biggest surprise = maximum value)
--   TIER 2 - High: Upset in group stage
--            (big surprise but lower elimination stakes)
--   TIER 3 - Elevated: No upset but knockout stage
--            (elimination stakes alone drive premium viewership)
--   TIER 4 - Standard: Expected result in group stage
--            (baseline inventory)
--
-- WHY TWO JOINS TO elo_ratings?
-- Each match has two teams. We need Elo ratings for both home and
-- away teams simultaneously to calculate the gap. This requires
-- joining elo_ratings twice — once aliased as 'eh' (elo home)
-- and once as 'ea' (elo away). Each join matches on a different
-- column (home_team vs away_team).
-- ================================================================

CREATE TABLE high_engagement_matches AS
SELECT
    m.fixture_id,
    m.match_date,
    m.round,
    m.group_name,
    m.stage_category,
    m.home_team,
    m.away_team,
    m.home_goals,
    m.away_goals,
    eh.elo_rating                      AS home_elo,
    ea.elo_rating                      AS away_elo,
    ABS(eh.elo_rating - ea.elo_rating) AS elo_gap,

    CASE
        WHEN m.home_goals > m.away_goals
             AND eh.elo_rating < ea.elo_rating - 100
        THEN 'UPSET: Lower-rated home team won'

        WHEN m.away_goals > m.home_goals
             AND ea.elo_rating < eh.elo_rating - 100
        THEN 'UPSET: Lower-rated away team won'

        WHEN m.home_goals > m.away_goals
        THEN 'Expected: Home win'

        WHEN m.away_goals > m.home_goals
        THEN 'Expected: Away win'

        ELSE 'Draw'
    END AS result_classification,

    CASE
        WHEN (m.home_goals > m.away_goals AND eh.elo_rating < ea.elo_rating - 100)
          OR (m.away_goals > m.home_goals AND ea.elo_rating < eh.elo_rating - 100)
        THEN
            CASE WHEN m.stage_category = 'Knockout Stage' THEN 'TIER 1 - Premium'
                 ELSE 'TIER 2 - High'
            END
        WHEN m.stage_category = 'Knockout Stage' THEN 'TIER 3 - Elevated'
        ELSE 'TIER 4 - Standard'
    END AS ad_slot_tier

FROM matches_clean m
JOIN elo_ratings eh ON m.home_team = eh.team_name
JOIN elo_ratings ea ON m.away_team = ea.team_name
WHERE m.is_completed = 1;

-- VIEW CONFIRMED UPSETS ranked by Elo gap (biggest surprises first)
SELECT
    match_date,
    home_team,
    away_team,
    home_goals,
    away_goals,
    home_elo,
    away_elo,
    elo_gap,
    result_classification,
    ad_slot_tier
FROM high_engagement_matches
WHERE result_classification LIKE 'UPSET%'
ORDER BY elo_gap DESC;

-- RESULTS AS OF JUNE 2026 (update as tournament progresses):
-- South Korea 2-1 Czech Republic  | Elo gap: 247 | TIER 2 - High
-- Morocco 1-0 Scotland            | Elo gap: 180 | TIER 2 - High
-- Mexico 3-0 Czech Republic       | Elo gap: 177 | TIER 2 - High
-- Ecuador 2-1 Germany             | Elo gap: 120 | TIER 2 - High

-- VIEW AD SLOT TIER DISTRIBUTION
SELECT ad_slot_tier, COUNT(*) AS match_count
FROM high_engagement_matches
GROUP BY ad_slot_tier
ORDER BY ad_slot_tier;


-- ================================================================
-- PHASE 9: EXPORT
--
-- Two tables are exported as CSVs for the Power BI dashboard layer.
-- Export method: MySQL Workbench Result Grid → Export icon
-- (The SELECT ... INTO OUTFILE method was avoided because it
-- requires secure_file_priv server configuration which is
-- restricted by default on Mac installations.)
--
-- Run each SELECT, then click the Export icon in the Result Grid.
-- Save to: worldcup_pipeline/data/processed/
-- ================================================================

-- EXPORT 1: final_standings.csv
SELECT * FROM final_standings ORDER BY group_name, group_rank;

-- EXPORT 2: high_engagement_matches.csv
SELECT * FROM high_engagement_matches ORDER BY elo_gap DESC;


-- ================================================================
-- DIAGNOSTIC QUERIES
-- (Keep these — useful for re-running checks after data refresh)
-- ================================================================

-- Check for team name mismatches between matches_clean and team_groups
SELECT DISTINCT tms.team
FROM team_match_stats tms
LEFT JOIN team_groups tg ON tms.team = tg.team_name
WHERE tg.team_name IS NULL;

-- Check for team name mismatches between matches_clean and elo_ratings
SELECT DISTINCT home_team
FROM matches_clean
WHERE is_completed = 1
AND home_team NOT IN (SELECT team_name FROM elo_ratings)
UNION
SELECT DISTINCT away_team
FROM matches_clean
WHERE is_completed = 1
AND away_team NOT IN (SELECT team_name FROM elo_ratings);

-- Check how many matches are coverable by the Elo join
SELECT COUNT(*) AS coverable_matches
FROM matches_clean m
JOIN elo_ratings eh ON m.home_team = eh.team_name
JOIN elo_ratings ea ON m.away_team = ea.team_name
WHERE m.is_completed = 1;

-- Full standings for a specific group (change 'A' to any group letter)
SELECT * FROM group_standings WHERE group_name = 'A';

-- All group leaders
SELECT group_name, team, points, goal_difference, group_rank
FROM final_standings
WHERE group_rank = 1
ORDER BY group_name;


-- ================================================================
-- REFRESH BLOCK
-- Run this section when re-importing fresh match data.
-- Always keep team_groups and elo_ratings — they don't change.
-- ================================================================
DROP TABLE IF EXISTS high_engagement_matches;
DROP TABLE IF EXISTS final_standings;
DROP TABLE IF EXISTS group_standings;
DROP TABLE IF EXISTS team_match_stats;
DROP TABLE IF EXISTS matches_clean;
DROP TABLE IF EXISTS raw_matches;


-- ================================================================
USE worldcup;

-- STEP 1: matches_clean
CREATE TABLE matches_clean AS
SELECT
    CAST(fixture_id AS SIGNED)                    AS fixture_id,
    LEFT(match_date, 10)                          AS match_date,
    TRIM(round)                                   AS round,
    TRIM(group_name)                              AS group_name,
    TRIM(status_short)                            AS status_short,
    TRIM(home_team)                               AS home_team,
    TRIM(away_team)                               AS away_team,
    CAST(NULLIF(home_goals, '') AS SIGNED)        AS home_goals,
    CAST(NULLIF(away_goals, '') AS SIGNED)        AS away_goals,
    CASE WHEN status_short = 'FT' THEN 1 ELSE 0 END AS is_completed,
    CASE
        WHEN group_name LIKE 'Group%' THEN 'Group Stage'
        ELSE 'Knockout Stage'
    END AS stage_category
FROM raw_matches;

-- STEP 2: team_match_stats
CREATE TABLE team_match_stats AS
SELECT
    fixture_id, match_date, stage_category,
    home_team AS team, away_team AS opponent,
    home_goals AS goals_for, away_goals AS goals_against,
    CASE WHEN home_goals > away_goals THEN 3 WHEN home_goals = away_goals THEN 1 ELSE 0 END AS points,
    CASE WHEN home_goals > away_goals THEN 1 ELSE 0 END AS win,
    CASE WHEN home_goals = away_goals THEN 1 ELSE 0 END AS draw,
    CASE WHEN home_goals < away_goals THEN 1 ELSE 0 END AS loss
FROM matches_clean WHERE is_completed = 1
UNION ALL
SELECT
    fixture_id, match_date, stage_category,
    away_team AS team, home_team AS opponent,
    away_goals AS goals_for, home_goals AS goals_against,
    CASE WHEN away_goals > home_goals THEN 3 WHEN away_goals = home_goals THEN 1 ELSE 0 END AS points,
    CASE WHEN away_goals > home_goals THEN 1 ELSE 0 END AS win,
    CASE WHEN away_goals = home_goals THEN 1 ELSE 0 END AS draw,
    CASE WHEN away_goals < home_goals THEN 1 ELSE 0 END AS loss
FROM matches_clean WHERE is_completed = 1;

-- STEP 3: group_standings
CREATE TABLE group_standings AS
SELECT
    tg.group_name,
    tms.team,
    COUNT(*)                                     AS played,
    SUM(tms.win)                                 AS wins,
    SUM(tms.draw)                                AS draws,
    SUM(tms.loss)                                AS losses,
    SUM(tms.goals_for)                           AS goals_for,
    SUM(tms.goals_against)                       AS goals_against,
    SUM(tms.goals_for) - SUM(tms.goals_against)  AS goal_difference,
    SUM(tms.points)                              AS points
FROM team_match_stats tms
JOIN team_groups tg ON tms.team = tg.team_name
GROUP BY tg.group_name, tms.team
ORDER BY tg.group_name, SUM(tms.points) DESC, (SUM(tms.goals_for) - SUM(tms.goals_against)) DESC;

-- STEP 4: final_standings
CREATE TABLE final_standings AS
SELECT
    group_name, team, played, wins, draws, losses,
    goals_for, goals_against, goal_difference, points,
    RANK() OVER (
        PARTITION BY group_name
        ORDER BY points DESC, goal_difference DESC, goals_for DESC
    ) AS group_rank,
    CASE
        WHEN RANK() OVER (PARTITION BY group_name ORDER BY points DESC, goal_difference DESC, goals_for DESC) = 1
        THEN 'Group Leader'
        WHEN RANK() OVER (PARTITION BY group_name ORDER BY points DESC, goal_difference DESC, goals_for DESC) = 2
        THEN 'Qualification Zone'
        WHEN RANK() OVER (PARTITION BY group_name ORDER BY points DESC, goal_difference DESC, goals_for DESC) = 3
        THEN 'Best-Third Contender'
        ELSE 'Eliminated'
    END AS qualification_status
FROM group_standings;

-- STEP 5: high_engagement_matches
CREATE TABLE high_engagement_matches AS
SELECT
    m.fixture_id, m.match_date, m.round, m.group_name,
    m.stage_category, m.home_team, m.away_team,
    m.home_goals, m.away_goals,
    eh.elo_rating AS home_elo,
    ea.elo_rating AS away_elo,
    ABS(eh.elo_rating - ea.elo_rating) AS elo_gap,
    CASE
        WHEN m.home_goals > m.away_goals AND eh.elo_rating < ea.elo_rating - 100
        THEN 'UPSET: Lower-rated home team won'
        WHEN m.away_goals > m.home_goals AND ea.elo_rating < eh.elo_rating - 100
        THEN 'UPSET: Lower-rated away team won'
        WHEN m.home_goals > m.away_goals THEN 'Expected: Home win'
        WHEN m.away_goals > m.home_goals THEN 'Expected: Away win'
        ELSE 'Draw'
    END AS result_classification,
    CASE
        WHEN (m.home_goals > m.away_goals AND eh.elo_rating < ea.elo_rating - 100)
          OR (m.away_goals > m.home_goals AND ea.elo_rating < eh.elo_rating - 100)
        THEN CASE WHEN m.stage_category = 'Knockout Stage' THEN 'TIER 1 - Premium'
                  ELSE 'TIER 2 - High' END
        WHEN m.stage_category = 'Knockout Stage' THEN 'TIER 3 - Elevated'
        ELSE 'TIER 4 - Standard'
    END AS ad_slot_tier
FROM matches_clean m
JOIN elo_ratings eh ON m.home_team = eh.team_name
JOIN elo_ratings ea ON m.away_team = ea.team_name
WHERE m.is_completed = 1;
----------------------------------------------------------------
SELECT match_date, home_team, away_team,
       home_goals, away_goals,
       home_elo, away_elo, elo_gap,
       result_classification, ad_slot_tier
FROM high_engagement_matches
WHERE result_classification LIKE 'UPSET%'
ORDER BY elo_gap DESC;
-- ================================================================


-- END OF QUERIES.SQL
-- Last updated: June 2026
-- Re-run extract_matches.py daily to refresh match data,
-- then re-run from PHASE 4 onwards to update all derived tables.
-- ================================================================